<a href="https://colab.research.google.com/github/suhaantammana/FeedBunny.github.io./blob/main/PRO_C125_Project_Boilerplate_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Archery-Target** is a game in which the players shoot sharp-pointed arrows at a round target having 10 rings.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg">

## RL Problem to Solve
Hit the center of the target with maximum reward

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Number of **State**: ?

Number of **Actions**: ?



In [1]:
#import libraries
import numpy as np
import random

## Reward Matrix
Reward Matrix represents states as rows and actions as columns with respective awards values assigned for a given state and action pair.

In [2]:
#Define reward matrix
rewards=np.array([10,9,8,7,6,5,4,3,2,1])

## Take Action Randomly

In [3]:
#Define shoot()
def shoot():
  return np.random.randint(0,10)

##Q-matrix

**Q-learning** is a reinforcement learning algorithm. Given the current state, it helps to find the best action to be taken by the agent.

**Q-matrix** represents reward received after a taking particular action in the current state. Initially, all the elements of the Q-matrix are zeroes.


In [4]:
#Create Q-matrix
import numpy as np
q_matrix=np.zeros([6,6])
print(q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


##Take Action

In [5]:
#Define take_action
def take_action(reward_matrix):

     #Call the shoot() function to get the action
     ring_index=shoot()
     #Print the action
     print("shoot at",ring_index)
     #Get the corresponding reward using Reward matrix
     reward=reward_matrix[ring_index]
     #Print reward
     print("reward for the shoot",reward)
     action=ring_index
     return action, reward



In [6]:
#Call take_action function
action_reward=take_action(rewards)


shoot at 8
reward for the shoot 2
